apiVersion: v1
kind: service
metadata:
   name: myjavaapp-rc
   labels:
      app: myjavaapp
spec:
  type: NodePort
  ports:
  - port: 8080
    nodeport: 30001
  selector:
    app: myjavaapp  


     